### **Problem 2: Stock Performance Visualizer**

**Scenario:**
Your manager wants a visual comparison of the stock performance of several major tech companies over the last year. Instead of manually downloading data, you will use Python libraries to fetch the data directly from financial APIs and create an interactive chart.

**Objectives:**
*   Learn how to install and import external libraries (`pandas`, `yfinance`, `plotly`).
*   Practice reading library documentation to understand how to use new functions.
*   Fetch real-world financial data programmatically.
*   Use `pandas` DataFrames to store and manipulate time-series data.
*   Create an interactive line chart with `plotly.express`.

#### **Step 1: Installation and Imports**
Before we start, you need to install the required libraries. The `!` command in a Jupyter cell lets you run shell commands, like `pip`.

Install:
-  pandas
-  yfinance
-  plotly

In [3]:
## Write the install command here

In [1]:
## Execute this to check is install went well
import pandas as pd
import yfinance as yf
import plotly.express as px

#### **Step 2: Learning the Tools - A Guide to Documentation**
A key skill for any developer is learning how to read documentation. You don't need to memorize every function; you just need to know how to look them up.

*   **yfinance:** This library connects to Yahoo! Finance. Its documentation is on its PyPI page or GitHub. A good starting point is looking for a "quickstart" or "examples" section.
    *   **Task:** Go on Goolge, and find a tutorial for Yahoo Finance. Here the method you are looking for is `yf.download`

*   **Pandas:** The most important data manipulation library. Its documentation is extensive. The "Getting Started" tutorials are excellent.
    *   **Task:** Lookup the '10 minutes to pandas' documentation on the official website

*   **Plotly Express:** A high-level library for creating beautiful, interactive plots. The best place to start is their gallery of examples.
    *   **Task:** Find the documentation for `plotly.express.line()`. What arguments do you need to specify the data, the x-axis, and the y-axis?

Note: While reading a documentation, it's a good practice to copy paste the command listed and try them on your own and witness the results
Note2: Lots of library are making an heavy usage of classes, remember the `dir` and `help` methods to investigate what methods you can use on a given class

In [2]:
import yfinance as yf
dir(yf)

['AsyncWebSocket',
 'EquityQuery',
 'FundQuery',
 'Industry',
 'Lookup',
 'Market',
 'PREDEFINED_SCREENER_QUERIES',
 'Search',
 'Sector',
 'Ticker',
 'Tickers',
 'WebSocket',
 'YfData',
 '_NOTSET',
 '__all__',
 '__author__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'base',
 'cache',
 'const',
 'data',
 'domain',
 'download',
 'enable_debug_mode',
 'exceptions',
 'live',
 'lookup',
 'multi',
 'pricing_pb2',
 'scrapers',
 'screen',
 'screener',
 'search',
 'set_config',
 'set_tz_cache_location',
 'shared',
 'ticker',
 'tickers',
 'utils',
 'version',
 'warnings']

In [5]:
dat = yf.Ticker("MSFT")
dir(dat)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_analysis',
 '_data',
 '_download_options',
 '_earnings',
 '_earnings_dates',
 '_expirations',
 '_fast_info',
 '_fetch_ticker_tz',
 '_financials',
 '_fundamentals',
 '_funds_data',
 '_get_earnings_dates_using_scrape',
 '_get_earnings_dates_using_screener',
 '_get_ticker_tz',
 '_holders',
 '_isin',
 '_lazy_load_price_history',
 '_message_handler',
 '_news',
 '_options2df',
 '_price_history',
 '_quote',
 '_shares',
 '_tz',
 '_underlying',
 'actions',
 'analyst_price_targets',
 'balance_sheet',
 'balancesheet',
 'calendar',
 'capital_gains',
 'cash_flow',
 'cashflow',
 'dividends',
 'earnings',
 'earnings_dates',
 'earnings_estimate',
 'earnings_history',
 'eps_revisions',
 'eps_trend',
 'fast_info',
 'financials',
 'funds_data',
 'get_actions',
 'get_analyst_price_targets',
 'get_balance_sheet',
 'get_balancesheet',
 'get_calendar',
 'get_capital_gains',
 'get_cash_flow',
 'get_cashflow',
 'get_dividends',
 'get_earnings',
 'get_earnings_dates',
 'get_earnings_estimate',
 'get_earnings_history',
 'get_eps_revisions',
 'get_eps_trend',
 'get_fast_info',
 'get_financials',
 'get_funds_data',
 'get_growth_estimates',
 'get_history_metadata',
 'get_income_stmt',
 'get_incomestmt',
 'get_info',
 'get_insider_purchases',
 'get_insider_roster_holders',
 'get_insider_transactions',
 'get_institutional_holders',
 'get_isin',
 'get_major_holders',
 'get_mutualfund_holders',
 'get_news',
 'get_recommendations',
 'get_recommendations_summary',
 'get_revenue_estimate',
 'get_sec_filings',
 'get_shares',
 'get_shares_full',
 'get_splits',
 'get_sustainability',
 'get_upgrades_downgrades',
 'growth_estimates',
 'history',
 'history_metadata',
 'income_stmt',
 'incomestmt',
 'info',
 'insider_purchases',
 'insider_roster_holders',
 'insider_transactions',
 'institutional_holders',
 'isin',
 'live',
 'major_holders',
 'mutualfund_holders',
 'news',
 'option_chain',
 'options',
 'quarterly_balance_sheet',
 'quarterly_balancesheet',
 'quarterly_cash_flow',
 'quarterly_cashflow',
 'quarterly_earnings',
 'quarterly_financials',
 'quarterly_income_stmt',
 'quarterly_incomestmt',
 'recommendations',
 'recommendations_summary',
 'revenue_estimate',
 'sec_filings',
 'session',
 'shares',
 'splits',
 'sustainability',
 'ticker',
 'ttm_cash_flow',
 'ttm_cashflow',
 'ttm_financials',
 'ttm_income_stmt',
 'ttm_incomestmt',
 'upgrades_downgrades',
 'ws']

In [11]:
dat.history(period='1mo')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-09-08 00:00:00-04:00,498.109985,501.200012,495.029999,498.200012,16771000,0.0,0.0
2025-09-09 00:00:00-04:00,501.429993,502.250000,497.700012,498.410004,14410500,0.0,0.0
2025-09-10 00:00:00-04:00,502.980011,503.230011,496.720001,500.369995,21611800,0.0,0.0
2025-09-11 00:00:00-04:00,502.250000,503.170013,497.880005,501.010010,18881600,0.0,0.0
2025-09-12 00:00:00-04:00,506.649994,512.549988,503.850006,509.899994,23624900,0.0,0.0
2025-09-15 00:00:00-04:00,508.790009,515.469971,507.000000,515.359985,17143800,0.0,0.0
2025-09-16 00:00:00-04:00,516.880005,517.229980,508.600006,509.040009,19711900,0.0,0.0
2025-09-17 00:00:00-04:00,510.619995,511.290009,505.929993,510.019989,15816600,0.0,0.0
2025-09-18 00:00:00-04:00,511.489990,513.070007,507.660004,508.450012,18913700,0.0,0.0
2025-09-19 00:00:00-04:00,510.559998,519.299988,510.309998,517.929993,52474100,0.0,0.0
2025-09-22 00:00:00-04:00,515.590027,517.739990,512.539978,514.450012,20009300,0.0,0.0
2025-09-23 00:00:00-04:00,513.799988,514.590027,507.309998,509.230011,19799600,0.0,0.0
2025-09-24 00:00:00-04:00,510.380005,512.479980,506.920013,510.149994,13533700,0.0,0.0
2025-09-25 00:00:00-04:00,508.299988,510.010010,505.040009,507.029999,15786500,0.0,0.0
2025-09-26 00:00:00-04:00,510.059998,513.940002,506.619995,511.459991,16213100,0.0,0.0
2025-09-29 00:00:00-04:00,511.500000,516.849976,508.880005,514.599976,17617800,0.0,0.0
2025-09-30 00:00:00-04:00,513.239990,518.159973,509.660004,517.950012,19728200,0.0,0.0
2025-10-01 00:00:00-04:00,514.799988,520.510010,511.690002,519.710022,22632300,0.0,0.0
2025-10-02 00:00:00-04:00,517.640015,521.599976,510.679993,515.739990,21222900,0.0,0.0
2025-10-03 00:00:00-04:00,517.099976,520.489990,515.000000,517.349976,15112300,0.0,0.0
2025-10-06 00:00:00-04:00,518.609985,531.030029,518.200012,528.570007,21388600,0.0,0.0
2025-10-07 00:00:00-04:00,528.289978,529.799988,521.440002,523.979980,14601600,0.0,0.0

In [6]:
help(dat.get_news)

Help on method get_news in module yfinance.base:

get_news(count=10, tab='news', proxy=<object object at 0x714d73eb8310>) -> list method of yfinance.ticker.Ticker instance
    Allowed options for tab: "news", "all", "press releases

#### **Step 3: Fetching Stock Data**
Using what you learned from the `yfinance` documentation, fetch the historical stock data for a few tickers.

*   Define a list of tickers (e.g., `'MSFT'`, `'AAPL'`, `'GOOG'`, `'AMZN'`).
*   Define a start and end date (e.g., one year of data).
*   Use `yf.download()` to get the data.
*   The result is a pandas DataFrame. Print the first 5 rows using the `.head()` method to inspect it.
*   If the result is not a pandas DataFrame, find a way to convert it as a pandas dataframe

Note: yf.download returns a multiindex dataframe by default. You can flatten it by investigating the methods .reset_index (on rows) and the assignation of .columns (on columns)

In [12]:
import yfinance as yf
tickers = ['MSFT', 'AAPL', 'GOOG']

data = yf.download(tickers)

depivoted = data.stack(level=['Price', 'Ticker']).reset_index()
depivoted.columns = ['Date'] + depivoted.columns[1:].tolist()

result = depivoted.pivot(
    index=['Date', 'Ticker'],
    columns='Price',
    values=0
).reset_index()

result.head()

/tmp/ipykernel_117563/4018665266.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(tickers)
[*********************100%***********************]  3 of 3 completed
/tmp/ipykernel_117563/4018665266.py:6: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  depivoted = data.stack(level=['Price', 'Ticker']).reset_index()

Price,Date,Ticker,Close,High,Low,Open,Volume
0,2025-09-08,AAPL,237.880005,240.149994,236.339996,239.300003,48999500.0
1,2025-09-08,GOOG,234.160004,238.399994,233.729996,235.789993,23128800.0
2,2025-09-08,MSFT,498.200012,501.200012,495.029999,498.109985,16771000.0
3,2025-09-09,AAPL,234.350006,238.779999,233.360001,237.000000,66313900.0
4,2025-09-09,GOOG,239.940002,240.589996,233.380005,234.190002,22854800.0

In [15]:
import pandas as pd
pd.DataFrame(result.to_dict(orient="records"))

,Date,Ticker,Close,High,Low,Open,Volume
0,2025-09-08,AAPL,237.880005,240.149994,236.339996,239.300003,48999500.0
1,2025-09-08,GOOG,234.160004,238.399994,233.729996,235.789993,23128800.0
2,2025-09-08,MSFT,498.200012,501.200012,495.029999,498.109985,16771000.0
3,2025-09-09,AAPL,234.350006,238.779999,233.360001,237.000000,66313900.0
4,2025-09-09,GOOG,239.940002,240.589996,233.380005,234.190002,22854800.0
...,...,...,...,...,...,...,...
61,2025-10-06,GOOG,251.509995,252.199997,245.690002,245.779999,18309000.0
62,2025-10-06,MSFT,528.570007,531.030029,518.200012,518.609985,21388600.0
63,2025-10-07,AAPL,256.480011,257.399994,255.429993,256.809998,31923700.0
64,2025-10-07,GOOG,247.130005,251.550003,246.809998,248.929993,13802700.0
65,2025-10-07,MSFT,523.979980,529.799988,521.440002,528.289978,14601600.0

In [ ]:
result.to_excel('tickers.xlsx')

In [11]:
result.index

RangeIndex(start=0, stop=63, step=1)

#### **Step 4: Select and Prepare the Data for Plotting**
The DataFrame you downloaded has a multi-level column structure. For plotting, we only need the "Adjusted Close" price, which accounts for dividends and stock splits.

*   Select the `'Adj Close'` column from the `stock_data` DataFrame.
*   Pandas makes this easy: `adj_close_data = stock_data['Adj Close']`.
*   Print the head of your new `adj_close_data` DataFrame to see the cleaned data.


Note: When using a dataframe, you can use the .loc method to select a specific column,

In [16]:
result.columns

Index(['Date', 'Ticker', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object', name='Price')

In [17]:
result.index

RangeIndex(start=0, stop=66, step=1)

In [23]:
aapl_stock = result.loc[result['Ticker'] == "AAPL", ['Date',"Close"]]

#### **Step 5: Create the Interactive Plot**
Now, use `plotly.express` to visualize the data. With Plotly, you can create a rich, interactive chart with a single line of code.

*   Use `px.line()` to create the plot.
*   Pass your `adj_close_data` DataFrame as the first argument.
*   Provide a title for your chart (e.g., "Tech Stock Performance 2023").
*   Add labels for the x and y axes using the `labels` argument (e.g., `labels={'value': 'Adjusted Close Price ($)', 'variable': 'Ticker'}`).

In [25]:
import plotly.express as px

px.line(
    aapl_stock,
    x = "Date",
    y = "Close"
)

In [26]:
result.head()

Price,Date,Ticker,Close,High,Low,Open,Volume
0,2025-09-08,AAPL,237.880005,240.149994,236.339996,239.300003,48999500.0
1,2025-09-08,GOOG,234.160004,238.399994,233.729996,235.789993,23128800.0
2,2025-09-08,MSFT,498.200012,501.200012,495.029999,498.109985,16771000.0
3,2025-09-09,AAPL,234.350006,238.779999,233.360001,237.000000,66313900.0
4,2025-09-09,GOOG,239.940002,240.589996,233.380005,234.190002,22854800.0